# Generated by Django 2.2.8 on 2019-12-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0004_auto_20191210_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
